# Production Environment Overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: austa-care

bases:
- ../../base

commonLabels:
  environment: production
  
commonAnnotations:
  environment: production

# Production-specific patches
patchesStrategicMerge:
- deployment-patches.yaml
- ingress-patches.yaml
- monitoring-patches.yaml

# Production replicas
replicas:
- name: austa-backend-api
  count: 5
- name: austa-frontend-pwa
  count: 3
- name: austa-whatsapp-webhook
  count: 3
- name: austa-ml-inference
  count: 3

# Production images with specific versions
images:
- name: austa-care/backend
  newName: 123456789.dkr.ecr.us-east-1.amazonaws.com/austa-care/backend
  newTag: v1.2.3
- name: austa-care/frontend
  newName: 123456789.dkr.ecr.us-east-1.amazonaws.com/austa-care/frontend
  newTag: v1.2.3
- name: austa-care/whatsapp-webhook
  newName: 123456789.dkr.ecr.us-east-1.amazonaws.com/austa-care/whatsapp
  newTag: v1.2.3
- name: austa-care/ml-inference
  newName: 123456789.dkr.ecr.us-east-1.amazonaws.com/austa-care/ml
  newTag: v1.2.3
- name: austa-care/model-downloader
  newName: 123456789.dkr.ecr.us-east-1.amazonaws.com/austa-care/model-downloader
  newTag: v1.2.3

# Production config
configMapGenerator:
- name: austa-frontend-config
  behavior: merge
  literals:
  - whatsapp-widget-id=prod-widget-xyz789
- name: austa-ml-config
  behavior: merge
  literals:
  - s3-model-bucket=austa-ml-models-prod

# Production patches for enhanced security and performance
patches:
# Increase resource limits for production
- target:
    kind: Deployment
    name: austa-backend-api
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 500m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 1Gi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 2000m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 4Gi

# Production HPA settings
- target:
    kind: HorizontalPodAutoscaler
    name: austa-backend-api-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 5
    - op: replace
      path: /spec/maxReplicas
      value: 50
    - op: replace
      path: /spec/metrics/0/resource/target/averageUtilization
      value: 60

# Production ML resources
- target:
    kind: Deployment
    name: austa-ml-inference
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 8Gi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 32Gi

# Production PDB settings
- target:
    kind: PodDisruptionBudget
    name: austa-whatsapp-pdb
  patch: |-
    - op: replace
      path: /spec/minAvailable
      value: 2

# Add production-specific components
resources:
- cluster-autoscaler.yaml
- backup-cronjob.yaml
- monitoring-extras.yaml