# Frontend PWA Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: austa-frontend-pwa
  namespace: austa-care
  labels:
    app: austa-frontend
    component: pwa
    version: v1
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: austa-frontend
      component: pwa
  template:
    metadata:
      labels:
        app: austa-frontend
        component: pwa
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: austa-frontend
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - austa-frontend
              topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: austa-care/frontend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: NGINX_ENTRYPOINT_QUIET_LOGS
          value: "1"
        - name: API_URL
          value: "https://api.austacare.com"
        - name: WHATSAPP_WIDGET_ID
          valueFrom:
            configMapKeyRef:
              name: austa-frontend-config
              key: whatsapp-widget-id
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: cache
          mountPath: /var/cache/nginx
        - name: run
          mountPath: /var/run
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
      volumes:
      - name: nginx-config
        configMap:
          name: austa-frontend-nginx-config
      - name: cache
        emptyDir: {}
      - name: run
        emptyDir: {}
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: austa-frontend
  namespace: austa-care
  labels:
    app: austa-frontend