_format_version: "3.0"
_transform: true

# Kong API Gateway Configuration for AUSTA Care Platform

# Upstreams - Backend service targets
upstreams:
  - name: austa-backend
    algorithm: round-robin
    slots: 10000
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 5
          successes: 2
        unhealthy:
          interval: 5
          tcp_failures: 3
          http_failures: 3
      passive:
        healthy:
          successes: 5
        unhealthy:
          http_failures: 5
          tcp_failures: 5
    targets:
      - target: backend:3000
        weight: 100

  - name: whatsapp-service
    algorithm: least-connections
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 10
    targets:
      - target: whatsapp:3001
        weight: 100

  - name: ml-service
    algorithm: round-robin
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 10
    targets:
      - target: ml-service:5000
        weight: 100

# Services - API service definitions
services:
  # Main Backend API
  - name: backend-api
    protocol: http
    host: austa-backend
    port: 80
    retries: 3
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    routes:
      - name: backend-route
        protocols:
          - http
          - https
        paths:
          - /api/v1
        strip_path: false
        preserve_host: true

  # WhatsApp Integration Service
  - name: whatsapp-api
    protocol: http
    host: whatsapp-service
    port: 80
    retries: 2
    routes:
      - name: whatsapp-route
        protocols:
          - http
          - https
        paths:
          - /api/v1/whatsapp
        strip_path: false

  # ML/AI Service
  - name: ml-api
    protocol: http
    host: ml-service
    port: 80
    retries: 2
    routes:
      - name: ml-route
        protocols:
          - http
          - https
        paths:
          - /api/v1/ml
          - /api/v1/ai
        strip_path: false

  # WebSocket Service
  - name: websocket-api
    protocol: http
    host: austa-backend
    port: 80
    routes:
      - name: websocket-route
        protocols:
          - ws
          - wss
        paths:
          - /ws
        strip_path: false

# Global Plugins
plugins:
  # CORS
  - name: cors
    config:
      origins:
        - http://localhost:3000
        - http://localhost:5173
        - https://app.austacare.com
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
      exposed_headers:
        - X-Auth-Token
        - X-Request-Id
      credentials: true
      max_age: 3600

  # Rate Limiting
  - name: rate-limiting
    config:
      minute: 60
      hour: 1000
      policy: local
      fault_tolerant: true
      hide_client_headers: false
      redis_host: redis
      redis_port: 6379

  # Request Size Limiting
  - name: request-size-limiting
    config:
      allowed_payload_size: 10
      size_unit: megabytes

  # Security Headers
  - name: response-transformer
    config:
      add:
        headers:
          - X-Frame-Options:DENY
          - X-Content-Type-Options:nosniff
          - X-XSS-Protection:1; mode=block
          - Strict-Transport-Security:max-age=31536000; includeSubDomains

  # Request ID
  - name: correlation-id
    config:
      header_name: X-Request-Id
      generator: uuid
      echo_downstream: true

  # Logging
  - name: http-log
    config:
      http_endpoint: http://logging-service:8080/logs
      method: POST
      timeout: 10000
      keepalive: 60000
      flush_timeout: 2
      retry_count: 10

  # Prometheus Metrics
  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

# Service-specific plugins
services:
  - name: backend-api
    plugins:
      # JWT Authentication
      - name: jwt
        config:
          claims_to_verify:
            - exp
          key_claim_name: iss
          secret_is_base64: false
          anonymous: 53e64088-9f32-4e26-a51a-9466ba3c7c7f
          run_on_preflight: false

      # Request Validation
      - name: request-validator
        config:
          body_schema: |
            {
              "type": "object",
              "required": ["data"],
              "properties": {
                "data": {
                  "type": "object"
                }
              }
            }
          allowed_content_types:
            - application/json
          version: draft7

      # IP Restriction (for admin endpoints)
      - name: ip-restriction
        config:
          allow:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
        route: admin-route

  - name: whatsapp-api
    plugins:
      # WhatsApp-specific rate limiting
      - name: rate-limiting
        config:
          minute: 30
          policy: local
          fault_tolerant: true

      # Request transformation
      - name: request-transformer
        config:
          add:
            headers:
              - X-WhatsApp-Service:true

  - name: ml-api
    plugins:
      # Higher timeout for ML operations
      - name: request-termination
        config:
          status_code: 408
          message: "ML request timeout"
          trigger:
            read_timeout: 300000

      # Cache ML predictions
      - name: proxy-cache
        config:
          response_code:
            - 200
          request_method:
            - GET
            - POST
          content_type:
            - application/json
          cache_ttl: 3600
          strategy: memory

# Consumers (API users)
consumers:
  # Anonymous consumer for unauthenticated requests
  - username: anonymous
    custom_id: 53e64088-9f32-4e26-a51a-9466ba3c7c7f
    
  # Service accounts
  - username: frontend-app
    custom_id: frontend-001
    
  - username: mobile-app
    custom_id: mobile-001
    
  - username: admin-dashboard
    custom_id: admin-001

# ACLs
acls:
  - consumer: frontend-app
    group: frontend
    
  - consumer: mobile-app
    group: mobile
    
  - consumer: admin-dashboard
    group: admin

# Rate limiting tiers
plugins:
  - name: rate-limiting
    consumer: frontend-app
    config:
      minute: 100
      hour: 5000
      
  - name: rate-limiting
    consumer: mobile-app
    config:
      minute: 60
      hour: 3000
      
  - name: rate-limiting
    consumer: admin-dashboard
    config:
      minute: 200
      hour: 10000