# WhatsApp Webhook Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: austa-whatsapp-webhook
  namespace: austa-care
  labels:
    app: austa-whatsapp
    component: webhook
    version: v1
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: austa-whatsapp
      component: webhook
  template:
    metadata:
      labels:
        app: austa-whatsapp
        component: webhook
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: austa-whatsapp
      securityContext:
        runAsNonRoot: true
        runAsUser: 10002
        fsGroup: 10002
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - austa-whatsapp
            topologyKey: kubernetes.io/hostname
      containers:
      - name: webhook
        image: austa-care/whatsapp-webhook:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3001
          protocol: TCP
        - name: metrics
          containerPort: 9091
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: WHATSAPP_VERIFY_TOKEN
          valueFrom:
            secretKeyRef:
              name: austa-whatsapp-secret
              key: verify-token
        - name: WHATSAPP_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: austa-whatsapp-secret
              key: access-token
        - name: WHATSAPP_PHONE_NUMBER_ID
          valueFrom:
            secretKeyRef:
              name: austa-whatsapp-secret
              key: phone-number-id
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: austa-redis-secret
              key: connection-string
        - name: BACKEND_API_URL
          value: "http://austa-backend-api.austa-care.svc.cluster.local"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/startup
            port: http
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 20
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: tmp
        emptyDir: {}
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: austa-whatsapp
  namespace: austa-care
  labels:
    app: austa-whatsapp
---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: austa-whatsapp-pdb
  namespace: austa-care
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: austa-whatsapp
      component: webhook