# Development Deployment Patches
# Backend API patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: austa-backend-api
spec:
  template:
    spec:
      containers:
      - name: api
        env:
        - name: NODE_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "debug"
        - name: DATABASE_URL
          value: "postgresql://postgres:devpassword@postgres-dev:5432/austacare_dev?sslmode=disable"
        - name: REDIS_URL
          value: "redis://redis-dev:6379/0"
---
# Frontend PWA patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: austa-frontend-pwa
spec:
  template:
    spec:
      containers:
      - name: nginx
        env:
        - name: API_URL
          value: "http://dev-api.austacare.local"
---
# WhatsApp webhook patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: austa-whatsapp-webhook
spec:
  template:
    spec:
      containers:
      - name: webhook
        env:
        - name: NODE_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "debug"
---
# ML Inference patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: austa-ml-inference
spec:
  template:
    spec:
      containers:
      - name: inference
        env:
        - name: PYTHON_ENV
          value: "development"
        - name: MODEL_CACHE_ENABLED
          value: "false"
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
            nvidia.com/gpu: 0
          limits:
            cpu: 1000m
            memory: 4Gi
            nvidia.com/gpu: 0